defaults: &defaults
  username: root
  password: welcome
  host: 127.0.0.1
  adapter: mysql2
  encoding: utf8

development:
  database: staffomatic_example_add_on_development
  <<: *defaults

production:
  database: staffomatic_example_add_on_production
  <<: *defaults
